# pixel space task with adaptive gamma correction
pixel:
  mcmc_sampler_config:  
    num_steps: 100
    lr: 2e-5
    tau: 0.01
    lr_min_ratio: 0.01
    mc_algo: langevin
    prior_solver: gaussian
  
  operator:
    name: hdr_adaptive_gamma
    scale: 2
    sigma: 0.05
    alpha: 1.5
    beta: 0.5

# pixel space task with hmc and adaptive gamma correction
pixel_hmc:
  mcmc_sampler_config:  
    num_steps: 100
    lr: 2.18e-5
    tau: 0.01
    lr_min_ratio: 0.013
    momentum: 0.23
    mc_algo: hmc
    prior_solver: gaussian
  
  operator:
    name: hdr_adaptive_gamma
    scale: 2
    sigma: 0.05
    alpha: 1.5
    beta: 0.5

# latent diffusion model with adaptive gamma correction
ldm: 
  mcmc_sampler_config: 
    num_steps: 38
    lr: 4.52e-06
    tau: 0.01
    lr_min_ratio: 0.015
    momentum: 0.58
    mc_algo: hmc
    prior_solver: gaussian
  
  operator:
    name: hdr_adaptive_gamma
    scale: 2
    sigma: 0.05
    alpha: 1.5
    beta: 0.5

# stable diffusion with adaptive gamma correction
sd: 
  mcmc_sampler_config: 
    num_steps: 45
    lr: 1.0e-05
    tau: 0.01
    lr_min_ratio: 1
    momentum: 0.7
    mc_algo: hmc
    prior_solver: gaussian
  
  operator:
    name: hdr_adaptive_gamma
    scale: 2
    sigma: 0.01
    alpha: 1.5
    beta: 0.5
